#!/usr/bin/python                                                                   
                                                                                    
import sys                                                                          
import itertools                                                                    
                                                                                    
out = open('passwordList', 'a')                                                     
                                                                                    
for item in itertools.product(xrange(10), repeat=4):                                
        password = 'UoMYTrfrBFHyQXmg6gzctqAwOmw1IohZ ' + ''.join(map(str, item))    
        out.write(password + '\n')                                                  
                                                                                    
out.close()                                                                         
